const { chromium } = require('playwright');
const D = __dirname + '/out/';
(async () => {
  const b = await chromium.launch();
  const ctx = await b.newContext({ viewport: { width: 1180, height: 820 }, timezoneId: 'America/Chicago' });
  const p = await ctx.newPage();
  const errs = [];
  p.on('pageerror', e => errs.push('pageerror ' + e.message));
  p.on('console', m => { if (m.type() === 'error') errs.push('console ' + m.text()); });
  await p.clock.setFixedTime(new Date('2026-10-06T10:40:00-05:00'));
  await p.goto('http://localhost:8080/');
  await p.waitForTimeout(500);
  await p.screenshot({ path: D + '1-connect.png' });
  await p.fill('#connUrl', 'https://example.com/foo'); await p.fill('#connKey', 'abc'); await p.click('#connBtn');
  console.log('bad url msg:', await p.textContent('#connErr'));
  await p.evaluate(() => localStorage.setItem('tos.conn.v1', JSON.stringify({ url: 'http://127.0.0.1:8090/macros/s/test/exec', key: 'k'.repeat(64) })));
  await p.reload(); await p.waitForTimeout(1200);
  await p.screenshot({ path: D + '2-today.png' });
  console.log('today events:', await p.locator('.ev').count(), '| status:', (await p.textContent('#status')).trim());
  await p.locator('.ev', { hasText: 'Busy' }).first().click(); await p.waitForTimeout(200);
  await p.screenshot({ path: D + '3-detail.png' });
  await p.click('#detailClose');
  await p.click('[data-screen="week"]'); await p.waitForTimeout(900); await p.screenshot({ path: D + '4-week.png' });
  await p.click('[data-screen="month"]'); await p.waitForTimeout(1200); await p.screenshot({ path: D + '5-month.png' });
  console.log('month cells with items:', await p.locator('.moc .li').count());
  await p.click('#nextBtn'); await p.waitForTimeout(1000); console.log('next month title:', await p.textContent('#title'));
  await p.click('[data-screen="systems"]'); await p.waitForTimeout(300); await p.screenshot({ path: D + '6-systems.png', fullPage: true });
  await p.route('**/127.0.0.1:8090/**', r => r.abort());
  await p.click('[data-act="refresh"]'); await p.waitForTimeout(600);
  console.log('offline status:', (await p.textContent('#status')).trim());
  await p.click('[data-screen="today"]'); await p.waitForTimeout(300);
  console.log('cached events while offline:', await p.locator('.ev').count());
  await p.unroute('**/127.0.0.1:8090/**');
  await p.setViewportSize({ width: 400, height: 860 }); await p.waitForTimeout(300);
  await p.screenshot({ path: D + '7-phone.png' });
  console.log('phone scrollWidth:', await p.evaluate(() => document.documentElement.scrollWidth));
  console.log('sw registered:', await p.evaluate(async () => !!(await navigator.serviceWorker.getRegistration())));
  console.log('errors:', errs.filter(e => !/fonts\.g/.test(e) && !/ERR_FAILED|net::/.test(e)));
  await b.close();
})();
